export const blogs = [
	{ url: "twoweeksgame.blogspot.ru", type: "blogger" },
	{ url: "twoweeksgame2.blogspot.ru", type: "blogger" },
	{ url: "twoweeksgame3.blogspot.ru", type: "blogger" },
	{ url: "twoweeksgame6.blogspot.ru", type: "blogger" },
	{ url: "7.twoweeks.ru", type: "blogger" },
	{ url: "8.twoweeks.ru", type: "blogger" },
	{ url: "gd-twoweeksgame9.blogspot.ru", type: "blogger" },
	{ url: "9.twoweeks.ru", type: "blogger" },
	{ url: "x.twg.host", type: "blogger" },
	{ url: "twg11.blogspot.ru", type: "blogger" },
	{ url: "twg-eleven.blogspot.ru", type: "blogger" },
	{ url: "twg-12.blogspot.ru", type: "blogger" },
	{ url: "13.twoweeks.ru", type: "blogger" },
	{ url: "twgrebirth.blogspot.ru", type: "blogger" },
	{ url: "twgtogether.blogspot.ru", type: "blogger" },
	{ url: "16.twoweeks.ru", type: "blogger" },
	{ url: "twg17gameover.blogspot.ru", type: "blogger" },
	{ url: "twg18newgame.blogspot.ru", type: "blogger" },
	{ url: "twg20legitime.blogspot.ru", type: "blogger" },
];
